basePath: /api
definitions:
  app_pkg_validator.FieldError:
    properties:
      failed_field:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
  fiber.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  model.User:
    properties:
      created_at:
        example: "2023-01-07T18:09:15.237672Z"
        type: string
      email:
        example: example@email.com
        type: string
      first_name:
        example: John
        maxLength: 255
        minLength: 3
        type: string
      id:
        example: 31afbd8d-0312-4f18-87ee-24d5881a619e
        type: string
      last_name:
        example: Doe
        maxLength: 255
        minLength: 3
        type: string
      updated_at:
        example: "2023-01-07T18:09:15.237672Z"
        type: string
    required:
    - email
    - first_name
    type: object
  model.UserBase:
    properties:
      email:
        example: example@email.com
        type: string
      first_name:
        example: John
        maxLength: 255
        minLength: 3
        type: string
      last_name:
        example: Doe
        maxLength: 255
        minLength: 3
        type: string
    required:
    - email
    - first_name
    type: object
  model.Users:
    properties:
      data:
        items:
          $ref: '#/definitions/model.User'
        type: array
      limit:
        example: 100
        type: integer
      offset:
        example: 100
        type: integer
      total:
        example: 1000
        type: integer
    type: object
  validator.ErrorResponse:
    properties:
      error:
        type: boolean
      field_error:
        items:
          $ref: '#/definitions/app_pkg_validator.FieldError'
        type: array
    type: object
host: 127.0.0.1:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample service template.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Get users with options
      parameters:
      - description: limit
        in: query
        name: limit
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      - description: less than unix timestamp
        in: query
        name: lt_datetime
        type: integer
      - description: greater than unix timestamp
        in: query
        name: gt_datetime
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Users'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Get users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create new user
      parameters:
      - description: create User request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserBase'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          headers:
            Location:
              description: /users/:id
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/validator.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Create new user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user by id
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiber.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Delete user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Get user by id
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiber.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Get user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update existing user or create a new one
      parameters:
      - description: Update User request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          headers:
            Location:
              description: /users/:id
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/validator.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Error'
      summary: Update user
      tags:
      - users
swagger: "2.0"
